spring:
    application:
        name: @project.artifactId@
    main:
        logStartupInfo: false

info:
    app:
        name: @project.artifactId@
        version: @project.version@

logging:
    level:
        org:
            springframework: off
            hibernate: off
            apache: off

app:
    migration:
        csvSeparator: "|"
    persistence:
        transporter:
            fileSystem:
                temporalPath: "migration"