spring:
    application:
        name: @project.artifactId@
    main:
        logStartupInfo: false

info:
    app:
        name: @project.artifactId@
        version: @project.version@

logging:
    level:
        org:
            springframework: off
            hibernate: off
            apache: off

app:
    migration:
        extractor:
            csvSeparator: "|"
            pageSize: 1000
        loader:
            csvSeparator: "|"
        transporter:
            name: FILESYSTEM
        observer:
            name: LOG
        service:
            schedule: ${MIGRATION_SERVICE_SCHEDULE}
            timezone: ${MIGRATION_SERVICE_TIMEZONE}
            projectPath: ${MIGRATION_SERVICE_PROJECT_PATH}
            sourcePassword: ${MIGRATION_SERVICE_SOURCE_PASSWORD}
            targetPassword: ${MIGRATION_SERVICE_TARGET_PASSWORD}
    persistence:
        transporter:
            fileSystem:
                temporalPath: "migration"