spring:
    application:
        name: @project.artifactId@
    main:
        logStartupInfo: false

info:
    app:
        name: @project.artifactId@
        version: @project.version@

logging:
    level:
        org:
            springframework: off
            hibernate: off
            apache: off

app:
    migration:
        extractor:
            csvSeparator: "|"
            pageSize: 1000
        loader:
            csvSeparator: "|"
        transporter:
            name: FILESYSTEM
        observer:
            name: CONSOLE
    persistence:
        transporter:
            fileSystem:
                temporalPath: "migration"