spring:
    application:
        name: aws-sct-data-migrator

app:
    migration:
        csvSeparator: "|"
    persistence:
        transporter:
            fileSystem:
                temporalPath: "migration"